[package]
name = "containerd-shim"
version = "0.1.0"
authors = ["Maksym Pavlenko <pavlenko.maksym@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/mxpv/containerd-rust-extensions"
keywords = ["containerd", "shim", "containers"]
description = "containerd shim extension"

[dependencies]
go-flag = "0.1.0"
thiserror = "1.0"
log = { version = "0.4", features = ["std"] }
libc = "0.2.95"
nix = "0.22"
command-fds = "0.2.1"

containerd-shim-client = { path = "../shim-client", version = "0.1.0" }
