[package]
name = "shim"
version = "0.1.0"
authors = ["Maksym Pavlenko <pavlenko.maksym@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/mxpv/containerd-rust-extensions"

[dependencies]
go-flag = "0.1.0"
thiserror = "1.0"
log = { version = "0.4", features = ["std"] }
libc = "0.2.95"

containerd-protos = { path = "../protos" }
