[package]
name = "shim"
version = "0.1.0"
authors = ["Maksym Pavlenko <pavlenko.maksym@gmail.com>"]
edition = "2018"

[dependencies]
go-flag = "0.1.0"
thiserror = "1.0"

containerd-protos = { path = "../protos" }
