[package]
name = "containerd-shim-logging"
version = "0.1.0"
authors = ["Maksym Pavlenko <pavlenko.maksym@gmail.com>"]
edition = "2018"
description = "Logger extension for containerd v2 runtime"

[dev-dependencies]
systemd = { version = "0.9.0", default-features = false, features = ["journal"] }
