[package]
name = "containerd-shim-protos"
version = "0.1.0"
authors = ["Maksym Pavlenko <pavlenko.maksym@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/mxpv/containerd-rust-extensions"
description = "TTRPC bindings for containerd shim interfaces"
keywords = ["containerd", "shim", "containers", "ttrpc", "client"]
categories = ["api-bindings"]

[dependencies]
protobuf = "2.23.0"

# Need the following PRs from `master` branch:
# - https://github.com/containerd/ttrpc-rust/pull/93
# - https://github.com/containerd/ttrpc-rust/pull/101
# - https://github.com/containerd/ttrpc-rust/pull/102
ttrpc = { git = "https://github.com/containerd/ttrpc-rust.git", rev = "c96574c9e359fc03e74a4455180d5ad125340b4a" }

[build-dependencies]
ttrpc-codegen = "0.2"
