[package]
name = "containerd-shim-protos"
version = "0.1.0"
authors = ["Maksym Pavlenko <pavlenko.maksym@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/mxpv/containerd-rust-extensions"
description = "TTRPC bindings for containerd shim interfaces"
keywords = ["containerd", "shim", "containers", "ttrpc", "client"]
categories = ["api-bindings"]

[dependencies]
protobuf = "2.23.0"
# Needs `Client::connect` to be published on crates.io
# PR: https://github.com/containerd/ttrpc-rust/pull/93
ttrpc = { git = "https://github.com/containerd/ttrpc-rust.git", rev = "da67137a8b89d6b796cb7e826ba2f6db2eed8f9e" }

[build-dependencies]
ttrpc-codegen = "0.2"
