name: CI
on: [push, pull_request]

jobs:
  checks:
    name: Checks
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y libsystemd-dev
      - run: cargo check --examples --tests --all-targets
      - run: cargo fmt --all -- --check --files-with-diff
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo test --all-features
